name: appvotos
description: Votaciones 2023
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.0.2
  http: ^0.13.4
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  intl: 0.18.0
  json_path: 0.4.1
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.4
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  flutter_native_splash: 
  flutter_hooks: ^0.18.0
  overlay_support: ^1.2.0
  flutter_sequence_animation: any
  scrollable_positioned_list: 
  carousel_slider: ^4.0.0-nullsafety.0
  animate_do: ^2.0.0
  quickalert:
  cupertino_icons: ^1.0.5
  scratcher: ^2.3.0
  flutter_spinkit: ^5.1.0
  pinput: ^1.2.2
  get: 4.6.5
  flutter_svg: 2.0.7
  country_picker: 2.0.20
  qr_widget: ^4.1.0
  dio:
  flutter_bloc: ^8.0.0
  equatable:
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^2.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/ico.png'
  adaptive_icon_background: 'assets/icon/ico.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/vacio.png
    - assets/images/default_image.png
    
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf